# Generated by Django 3.2.10 on 2022-05-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('kinds', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('product_img_url', models.CharField(max_length=200)),
                ('convenience_store', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
            ],
        ),
    ]
